import subprocess
import tempfile
import textwrap
import unittest
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
UPGRADER = ROOT / "upgrade-llmctl.sh"
MANIFEST = ROOT / "upgrade-manifest.tsv"
MANAGER = (ROOT / "llmctl.sh").read_text(encoding="utf-8")
INSTALLER = (ROOT / "install-llm-cluster.sh").read_text(encoding="utf-8")


class ControlPlaneUpgradeTests(unittest.TestCase):
    def build_archive(self, archive: Path) -> None:
        files = [
            "llmctl.sh",
            "upgrade-llmctl.sh",
            "upgrade-manifest.tsv",
            "lib/model_catalog.py",
            "lib/runtime_optimizer.py",
            "lib/gateway_config.py",
            "lib/account_portal.py",
            "lib/llm_benchmark.py",
            "systemd/llm-keepwarm.service",
            "systemd/llm-keepwarm.timer",
        ]
        files.extend(
            str(path.relative_to(ROOT))
            for path in sorted((ROOT / "lib/account_portal_ui").rglob("*"))
            if path.is_file()
        )
        with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as handle:
            for relative in files:
                handle.write(ROOT / relative, f"LLMCtl-main/{relative}")

    def test_manifest_is_limited_to_control_plane_paths(self):
        entries = []
        for raw_line in MANIFEST.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            entry_type, source, destination, mode, restart = line.split()
            entries.append((entry_type, source, destination, mode, restart))

        self.assertGreaterEqual(len(entries), 7)
        self.assertIn(
            ("file", "llmctl.sh", "/usr/local/sbin/llmctl", "0755", "none"),
            entries,
        )
        for entry_type, source, destination, mode, restart in entries:
            self.assertIn(entry_type, {"file", "dir"})
            self.assertTrue(
                destination == "/usr/local/sbin/llmctl"
                or destination.startswith("/usr/local/lib/llm-cluster/")
                or destination in {
                    "/etc/systemd/system/llm-keepwarm.service",
                    "/etc/systemd/system/llm-keepwarm.timer",
                }
            )
            self.assertNotIn("llm-worker@", destination.lower())
            self.assertRegex(mode, r"^0[0-7]{3}$")
            self.assertIn(restart, {"none", "account", "systemd"})

    def test_llmctl_delegates_upgrade_and_installer_installs_helper(self):
        self.assertIn("cmd_upgrade() {", MANAGER)
        self.assertIn('exec "${CONTROL_PLANE_UPDATER}" --lang', MANAGER)
        self.assertIn('upgrade) cmd_upgrade "$@"', MANAGER)
        self.assertIn("llmctl upgrade --from-zip FILE", MANAGER)
        self.assertIn(
            'install -m 755 "${UPGRADER_SOURCE}" /usr/local/lib/llm-cluster/upgrade-llmctl.sh',
            INSTALLER,
        )

    def test_upgrader_preserves_runtime_and_only_refreshes_managed_nginx(self):
        source = UPGRADER.read_text(encoding="utf-8")
        self.assertIn('systemctl stop "${ACCOUNT_SERVICE}"', source)
        self.assertNotIn("systemctl stop llm-router", source)
        self.assertNotIn("systemctl restart llm-router", source)
        self.assertNotIn("systemctl stop llm-worker", source)
        self.assertNotIn("systemctl restart llm-worker", source)
        self.assertNotIn("systemctl restart docker", source)
        self.assertNotIn("nginx -s", source)
        self.assertIn("refresh_managed_nginx()", source)
        self.assertIn("'^# Generated by LLMCtl '", source)
        self.assertIn("/usr/local/sbin/llmctl nginx apply", source)
        self.assertIn("域名、80/443、证书和 TLS 仍由外部出口管理", source)
        self.assertIn("restore_control_plane()", source)
        self.assertIn("load_saved_proxy()", source)
        self.assertIn("prompt_new_proxy()", source)

    def test_local_zip_check_validates_without_deploying(self):
        with tempfile.TemporaryDirectory() as temporary:
            archive = Path(temporary) / "LLMCtl-main.zip"
            self.build_archive(archive)
            result = subprocess.run(
                [
                    "bash",
                    str(UPGRADER),
                    "--from-zip",
                    str(archive),
                    "--check",
                    "--non-interactive",
                    "--lang",
                    "zh",
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
                timeout=20,
                check=False,
            )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("升级包验证通过", result.stdout)
        self.assertIn("没有修改现有控制面或服务", result.stdout)

    def test_zip_path_traversal_is_rejected_before_deployment(self):
        with tempfile.TemporaryDirectory() as temporary:
            archive = Path(temporary) / "unsafe.zip"
            with zipfile.ZipFile(archive, "w") as handle:
                handle.writestr("../escape", "unsafe")
                handle.writestr("upgrade-manifest.tsv", "placeholder")
            result = subprocess.run(
                [
                    "bash",
                    str(UPGRADER),
                    "--from-zip",
                    str(archive),
                    "--check",
                    "--non-interactive",
                    "--lang",
                    "en",
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
                timeout=20,
                check=False,
            )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("unsafe ZIP path", result.stderr)

    def test_real_archive_timeout_prompts_for_proxy_and_retries(self):
        with tempfile.TemporaryDirectory() as temporary:
            temporary_path = Path(temporary)
            archive = temporary_path / "LLMCtl-main.zip"
            self.build_archive(archive)
            fake_bin = temporary_path / "bin"
            fake_bin.mkdir()
            fake_curl = fake_bin / "curl"
            fake_curl.write_text(
                textwrap.dedent(
                    """\
                    #!/usr/bin/env bash
                    set -eu
                    output=""
                    url=""
                    while (( $# )); do
                      case "$1" in
                        -o) output="$2"; shift 2 ;;
                        http://*|https://*) url="$1"; shift ;;
                        *) shift ;;
                      esac
                    done
                    if [[ "${url}" == *api.github.com* ]]; then
                      if [[ -n "${output}" && "${output}" != "/dev/null" ]]; then
                        printf '{"sha":"1111111111111111111111111111111111111111"}\n' >"${output}"
                      fi
                      exit 0
                    fi
                    if [[ "${url}" == */archive/*.zip ]]; then
                      if [[ -z "${HTTPS_PROXY:-${https_proxy:-}}" ]]; then exit 28; fi
                      cp "${FAKE_ARCHIVE_SOURCE}" "${output}"
                      exit 0
                    fi
                    exit 0
                    """
                ),
                encoding="utf-8",
            )
            fake_curl.chmod(0o755)
            environment = {
                **dict(__import__("os").environ),
                "PATH": f"{fake_bin}:{__import__('os').environ['PATH']}",
                "FAKE_ARCHIVE_SOURCE": str(archive),
            }
            result = subprocess.run(
                [
                    "bash",
                    str(UPGRADER),
                    "--check",
                    "--yes",
                    "--lang",
                    "zh",
                ],
                cwd=ROOT,
                env=environment,
                input="192.168.9.104\n1082\nhttp\n",
                text=True,
                capture_output=True,
                timeout=20,
                check=False,
            )
        self.assertEqual(result.returncode, 0, result.stderr)
        combined = result.stdout + result.stderr
        self.assertIn("GitHub 升级包下载直连失败（curl=28）", combined)
        self.assertIn("代理后的 GitHub 网络测试通过", combined)
        self.assertIn("正在通过代理重试GitHub 升级包下载", combined)
        self.assertIn("预检完成：没有修改现有控制面或服务", combined)


if __name__ == "__main__":
    unittest.main()
